# Generated by Django 4.2.7 on 2023-12-31 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(default="맛집", max_length=30),
            preserve_default=False,
        ),
    ]
