# Generated by Django 4.2.7 on 2024-01-04 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_post_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="category",
        ),
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.CharField(
                choices=[("RESTAURANT", "맛집"), ("HOBBY", "취미")],
                default="RESTAURANT",
                max_length=30,
            ),
            preserve_default=False,
        ),
    ]
